name: Build Custom

on:
  workflow_dispatch:

jobs:
  build-win10-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.13'
          architecture: x64

      - run: C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py cpp x64 win10
      - run: C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py hook x64 win10
      - run: C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py pyrt x64 3.13.13 win10
      - run: C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py merge x64 win10

      - uses: actions/upload-artifact@v7
        with:
          name: LunaTranslator_x64_custom
          path: src/build/LunaTranslator_x64
